### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by xisafe** [0Kee-Team/WatchAD#3]
Traceback (most recent call last):
  File "WatchAD.py", line 149, in <module>
    main()
  File "WatchAD.py", line 135, in main
    install(domain=options.domain, server=options.server, user=options.username, password=options.password)
  File "WatchAD.py", line 33, in install
    get_all_dc_names(domain)
  File "/opt/WatchAD/scripts/init_settings.py", line 193, in get_all_dc_names
    ldap_search = LDAPSearch(domain)
  File "/opt/WatchAD/tools/LDAPSearch.py", line 21, in __init__
    self.con = Connection(self._get_server(),
  File "/opt/WatchAD/tools/LDAPSearch.py", line 28, in _get_server
    return Server(main_config.ldap_account[self.domain]["server"], get_info=ALL)
KeyError: 'XXXXXXXX'

**Comment by xisafe** [comment]
[root@V093 WatchAD]# python3 WatchAD.py --install -d 360.cn -s dc01.360.cn -u admin -p password
2019-10-30 15:10:20,197 - WatchAD - INFO - Install the WatchAD ...
2019-10-30 15:10:20,198 - WatchAD - INFO - init the elasticsearch index template.
2019-10-30 15:10:20,206 - WatchAD - INFO - template "dc_log_template" already exists, delete it.
2019-10-30 15:10:20,281 - WatchAD - INFO - put template "dc_log_template" ...
2019-10-30 15:10:20,349 - WatchAD - INFO - template "krb5_ticket_template" already exists, delete it.
2019-10-30 15:10:20,403 - WatchAD - INFO - put template "krb5_ticket_template" ...
2019-10-30 15:10:20,480 - WatchAD - INFO - template "dc_traffic_template" already exists, delete it.
2019-10-30 15:10:20,551 - WatchAD - INFO - put template "dc_traffic_template" ...
2019-10-30 15:10:20,626 - WatchAD - INFO - template "user_activity_template" already exists, delete it.
2019-10-30 15:10:20,696 - WatchAD - INFO - put template "user_activity_template" ...
2019-10-30 15:10:20,764 - WatchAD - INFO - init the ldap configuration.
2019-10-30 15:10:20,814 - WatchAD - INFO - Search all domain controllers using LDAP.
Traceback (most recent call last):
  File "WatchAD.py", line 149, in <module>
    main()
  File "WatchAD.py", line 135, in main
    install(domain=options.domain, server=options.server, user=options.username, password=options.password)
  File "WatchAD.py", line 33, in install
    get_all_dc_names(domain)
  File "/opt/WatchAD/scripts/init_settings.py", line 193, in get_all_dc_names
    ldap_search = LDAPSearch(domain)
  File "/opt/WatchAD/tools/LDAPSearch.py", line 21, in __init__
    self.con = Connection(self._get_server(),
  File "/opt/WatchAD/tools/LDAPSearch.py", line 28, in _get_server
    return Server(main_config.ldap_account[self.domain]["server"], get_info=ALL)
KeyError: '360'

**Comment by xisafe** [comment]
self.domain=360和数据key360.cn不匹配

**Comment by Qianlitp** [comment]
I have already [fixed](https://github.com/0Kee-Team/WatchAD/commit/489acd6e885f009887cb41b45e4c43f8f23cea56) this problem.
