### ISSUE TITLE
start.py这个脚本是不是有问题啊？？

### ISSUE THREAD

**Issue by T4di5** [0Kee-Team/WatchAD#35]
Traceback (most recent call last):
  File "/home/polo/WatchAD/tools/database/Consumer.py", line 71, in callback
    self.handle_func(message)
  File "/home/polo/WatchAD/start.py", line 89, in do_analyze
    if data['type'] == "wineventlog":
KeyError:'type'

**Comment by T4di5** [comment]
Traceback (most recent call last):
  File "/home/polo/WatchAD/start.py", line 169, in <module>
    Engine().start()
  File "/home/polo/WatchAD/start.py", line 55, in start
    c.run(self.do_analyze)
  File "/home/polo/WatchAD/tools/database/Consumer.py", line 64, in run
    self.channel.start_consuming()
  File "/usr/local/lib/python3.6/dist-packages/pika/adapters/blocking_connection.py", line 1857, in start_consuming
    self._process_data_events(time_limit=None)
  File "/usr/local/lib/python3.6/dist-packages/pika/adapters/blocking_connection.py", line 2018, in _process_data_events
    self.connection.process_data_events(time_limit=time_limit)
  File "/usr/local/lib/python3.6/dist-packages/pika/adapters/blocking_connection.py", line 835, in process_data_events
    self._dispatch_channel_events()
  File "/usr/local/lib/python3.6/dist-packages/pika/adapters/blocking_connection.py", line 567, in _dispatch_channel_events
    impl_channel._get_cookie()._dispatch_events()
  File "/usr/local/lib/python3.6/dist-packages/pika/adapters/blocking_connection.py", line 1485, in _dispatch_events
    evt.properties, evt.body)
  File "/home/polo/WatchAD/tools/database/Consumer.py", line 71, in callback
    self.handle_func(message)
  File "/home/polo/WatchAD/start.py", line 89, in do_analyze
    if data['type'] == "wineventlog":
KeyError: 'type'

**Comment by Dean-1A** [comment]
winlogbeat版本不匹配，参考官方文档，调整winlogbeat的版本
