### ISSUE TITLE
初始化安装watchad.py时候报错

### ISSUE THREAD

**Issue by GeneralDuan** [0Kee-Team/WatchAD#46]
2022-06-11 00:24:54,309 - WatchAD - INFO - Install the WatchAD ...
2022-06-11 00:24:54,309 - WatchAD - INFO - init the elasticsearch index template.
2022-06-11 00:24:54,345 - WatchAD - INFO - template "dc_log_template" already exists, delete it.
2022-06-11 00:24:54,397 - WatchAD - INFO - put template "dc_log_template" ...
2022-06-11 00:24:54,418 - WatchAD - INFO - template "krb5_ticket_template" already exists, delete it.
2022-06-11 00:24:54,432 - WatchAD - INFO - put template "krb5_ticket_template" ...
2022-06-11 00:24:54,469 - WatchAD - INFO - template "dc_traffic_template" already exists, delete it.
2022-06-11 00:24:54,482 - WatchAD - INFO - put template "dc_traffic_template" ...
2022-06-11 00:24:54,507 - WatchAD - INFO - template "user_activity_template" already exists, delete it.
2022-06-11 00:24:54,513 - WatchAD - INFO - put template "user_activity_template" ...
2022-06-11 00:24:54,533 - WatchAD - INFO - init the ldap configuration.
2022-06-11 00:24:56,141 - WatchAD - INFO - Search all domain controllers using LDAP.
2022-06-11 00:24:56,529 - WatchAD - INFO - AD1
2022-06-11 00:24:56,529 - WatchAD - INFO - domain controller count: 1
2022-06-11 00:24:56,529 - WatchAD - INFO - Save all domain controllers to settings.
2022-06-11 00:24:57,283 - WatchAD - INFO - init other settings.
2022-06-11 00:24:57,598 - WatchAD - INFO - init sensitive groups.
2022-06-11 00:24:57,776 - WatchAD - INFO - Administrators,Account Operators,Server Operators,Print Operators,Backup Operators,Replicator,Remote Desktop Users,Network Configuration Operators,Incoming Forest Trust Builders,Domain Admins,Enterprise Admins,Schema Admins,DnsAdmins,Group Policy Creator Owners
2022-06-11 00:24:57,836 - WatchAD - INFO - set learning end time: 2022-06-21 07:24:57.836277
2022-06-11 00:24:57,884 - WatchAD - INFO - set crontab tasks.
Traceback (most recent call last):
  File "WatchAD.py", line 159, in <module>
    main()
  File "WatchAD.py", line 145, in main
    install(domain=options.domain, server=options.server, user=options.username, password=options.password)
  File "WatchAD.py", line 43, in install
    set_crontab_tasks()
  File "/root/WatchAD/scripts/init_settings.py", line 289, in set_crontab_tasks
    my_user_cron = CronTab(user=True)
TypeError: __init__() got an unexpected keyword argument 'user'

这里可以帮分析下问题点吗？

**Comment by Qianlitp** [comment]
能贴一下你的完整命令吗
